In [29]:
# Pandas and Numpy stack
import pandas as pd
import numpy as np

# Others
import copy

# Sklearn datasets
from sklearn.datasets import load_wine

# Scipy bootstrap
from scipy.stats import bootstrap

In [ ]:
# Load wine dataset
data = load_wine()
df = pd.concat([pd.DataFrame(data.data, columns=data.feature_names), 
               pd.DataFrame(data.target, columns=['target'])], 
               axis=1)
df.reset_index(drop=False, inplace=True, names=['id'])
#print(data.DESCR)

# Copy
df2=copy.deepcopy(df[['id', 'alcohol', 'target']])

In [74]:
# Non-grouped bootstrap sample
df_sample=df2.sample(n=10, replace=True, random_state=42,)
df_sample

      id  alcohol  target
102  102    12.34       1
92    92    12.69       1
14    14    14.38       0
106  106    12.25       1
71    71    13.86       1
20    20    14.06       0
102  102    12.34       1
121  121    11.56       1
74    74    11.96       1
87    87    11.65       1

In [72]:
for rep in range(5):
    temp=df2.sample(n=10, replace=True, random_state=42+rep,)
    temp['rep']=rep
    if rep==0:
        df_sample=temp
    else:
        df_sample=pd.concat([df_sample, temp], axis=0)
df_sample = df_sample[['id', 'rep'] + df_sample.columns[1:-1].to_list()]
df_sample

      id  rep  alcohol  target
102  102    0    12.34       1
92    92    0    12.69       1
14    14    0    14.38       0
106  106    0    12.25       1
71    71    0    13.86       1
20    20    0    14.06       0
102  102    0    12.34       1
121  121    0    11.56       1
74    74    0    11.96       1
87    87    0    11.65       1
68    68    1    13.34       1
64    64    1    12.17       1
49    49    1    13.94       0
21    21    1    12.93       0
58    58    1    13.72       0
16    16    1    14.30       0
51    51    1    13.83       0
145  145    1    13.16       2
91    91    1    12.00       1
110  110    1    11.46       1
20    20    2    14.06       0
163  163    2    12.96       2
173  173    2    13.71       2
59    59    2    12.37       1
131  131    2    12.88       2
96    96    2    11.81       1
84    84    2    11.84       1
131  131    2    12.88       2
120  120    2    11.45       1
151  151    2    12.79       2
158  158    3    14.34       2
131  131    3    12.88       2
124  124    3    11.87       1
32    32    3    13.68       0
95    95    3    12.47       1
163  163    3    12.96       2
68    68    3    13.34       1
121  121    3    11.56       1
120  120    3    11.45       1
15    15    3    13.63       0
69    69    4    12.21       1
40    40    4    13.56       0
116  116    4    11.82       1
147  147    4    12.87       2
146  146    4    13.88       2
93    93    4    12.29       1
60    60    4    12.33       1
155  155    4    13.17       2
130  130    4    12.86       2
72    72    4    13.49       1

In [59]:
chk=df2.groupby('target').sample(frac=0.2, replace=True, random_state=42)

print(df2['target'].value_counts()*.2)
print(chk['target'].value_counts())

target
1    14.2
0    11.8
2     9.6
Name: count, dtype: float64
target
1    14
0    12
2    10
Name: count, dtype: int64